### PR TITLE
Fix dropped set operations within a CTE in Snowflake

### LINKED ISSUE #1272: [BUG]: In Snowflake, set operations inside a CTE are dropped
### Current Behavior

At the moment set operations within a CTE seem to be dropped: only the first `SELECT` is present.

That is, this statement:
```sql
WITH a AS (SELECT 1, 2, 3),
     b AS (SELECT 4, 5, 6),
     c AS (
         SELECT * FROM a
         UNION
         SELECT * FROM b
     )
SELECT * FROM c;
```
transpiles to:
```sql
WITH a AS (SELECT 1, 2, 3),
     b AS (SELECT 4, 5, 6),
     c AS (SELECT * FROM a)
SELECT * FROM c;
```

### Expected Behavior

Instead it should transpile to:
```sql
WITH a AS (SELECT 1, 2, 3),
     b AS (SELECT 4, 5, 6),
     c AS (
         (SELECT * FROM a)
         UNION
         (SELECT * FROM b)
     )
SELECT * FROM c;
```

### PR DESCRIPTION
**Pull request by asnare**
This PR is stacked upon #1273 (and should not be merged prior to it) and fixes a problem whereby for Snowflake set operations within a CTE were not being correctly processed to the IR. In this situation the CTE was dropping everything from the first set operation onwards.

Resolves: #1272 

Testing:

 - [X] Updated existing unit test.
 - [x] New transpilation test.
 - [X] Functional tests.

### CODE REVIEW

**Review by vil1 — APPROVED** [review]
lgtm

File: tests/resources/functional/snowflake/core_engine/test_cte/nested_set_operation.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+WITH a AS (
+    SELECT 1, 2, 3
+    UNION
+    SELECT 4, 5, 6
+)
+SELECT * FROM a;
+
+-- databricks sql:
+WITH a AS (
+    (SELECT 1, 2, 3)
```
Comment (ericvergnaud) [inline tests/resources/functional/snowflake/core_engine/test_cte/nested_set_operation.sql:15]: See https://github.com/databrickslabs/remorph/issues/1284

**Review by ericvergnaud — APPROVED** [review]
LGTM
