### PR TITLE
Fix Snowflake precedence of `INTERSECT` with respect to other set operations

### LINKED ISSUE #1255: [TECH DEBT]: Handle the precedence of the `INTERSECT` set operation in the grammar(s) rather than in code
### Current Behavior

As part of #1227 it became clear that our grammars for set operations treat `INTERSECT`, `UNION` and `EXCEPT` as equivalent. However it turns out that `INTERSECT` has higher precedence than the others. Although this can be dealt with in code during conversion to the IR, it would be better if this was reflected by the grammar (which also simplifies the conversion to IR).

### Expected Behavior

The grammars should treat `INTERSECT` as having higher precedence than `UNION` and `EXCEPT`.

The rules of precedence for set operations are:
1. Parentheses
2. `INTERSECT`
3. `EXCEPT` and `UNION` ordered from left-to-right.

Given that `INTERSECT` is commutative, ordering is unimportant.

Needs to be fixed in:

 - [x] TSQL (#1259)
 - [x] Snowflake (#1288)

References:
 - https://learn.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-except-and-intersect-transact-sql?view=sql-server-ver16#:~:text=following%20precedence
 - https://docs.snowflake.com/en/sql-reference/operators-query#:~:text=precedence

Relevant grammar rules:
https://github.com/databrickslabs/remorph/blob/932080a1fca53ed201fe7129a4679e1ab856dd23/core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4#L3154-L3158
https://github.com/databrickslabs/remorph/blob/932080a1fca53ed201fe7129a4679e1ab856dd23/core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4#L2796-L2800

Changing the grammar will mean refactoring this code:
https://github.com/databrickslabs/remorph/blob/932080a1fca53ed201fe7129a4679e1ab856dd23/core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala#L79-L134

### PR DESCRIPTION
**Pull request by asnare**
This PR updates the Snowflake processing so that the precedence of `INTERSECT` is handled correctly. At present the set operations (`UNION`, `EXCEPT` and `INTERSECT`) are all handled left-to-right with equal precedence. However this is incorrect, Snowflake semantics are[^1], from highest to lowest:
1. Parenthesis
2. `INTERSECT`
3. `UNION [ALL]` and `MINUS`/`EXCEPT`

At the same level operators are processed from left to right.

Resolves #1255.

Tests coverage:
 - Unit tests.
 - Transpiler tests.
 - Functional tests.

Incidental changes include factoring out some of the tests that we run against TSQL so that the same tests can run against Snowflake.

[^1]: Reference: https://docs.snowflake.com/en/sql-reference/operators-query

### CODE REVIEW

File: core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala [hunk 1]
```diff
@@ -67,10 +67,16 @@ class SnowflakeAstBuilder(override val vc: SnowflakeVisitorCoordinator)
...
+      val query = ctx.queryExpression().accept(this)
+      Option(ctx.withExpression()).foldRight(query)(buildCTE)
+    }
+  }
+
+  override def visitQueryExpression(ctx: QueryExpressionContext): ir.LogicalPlan = {
     errorCheck(ctx).getOrElse {
       val select = ctx.selectStatement().accept(vc.relationBuilder)
-      val queryExpression = ctx.setOperators().asScala.foldLeft(select)(buildSetOperator)
-      Option(ctx.withExpression()).foldRight(queryExpression)(buildCTE)
```
Comment (jimidle) [inline core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala:73]: Does this violate the parameter list stuff, or no?

https://github.com/databricks/scala-style-guide?tab=readme-ov-file#multiple-parameter-lists

**Review by jimidle — APPROVED** [review]
LGTM - but I wonder about the multiple parameter lists - not a blocker though.

File: core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala (hunk 1 above)
Comment (asnare) [reply core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/SnowflakeAstBuilder.scala:73]: That's a good question. I interpret that guideline to be about declaring functions that use multiple parameter lists, which the `case class` is effectively doing.

In this example we're using them on a method declared by the standard library, which is not what I think the guideline is aimed at. (Such usage is unavoidable due to the way Scala libraries are often designed, especially if they take a function/closure as a parameter.)

**Review by ericvergnaud — APPROVED** [review]
LGTM
